CREATE TYPE status_type AS ENUM ('pending', 'done', 'deleted');

CREATE TABLE dropbox (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	desktop_path VARCHAR(300) NOT NULL UNIQUE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status status_type DEFAULT 'done',
	filename VARCHAR(300) NOT NULL
);

CREATE INDEX filename_index ON dropbox (filename);
CREATE INDEX status_index ON dropbox (status);
CREATE INDEX created_at_desc_idx ON dropbox (created_at DESC);

CREATE TABLE dropbox_cursors (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	dropbox_cursor VARCHAR(500) NOT NULL UNIQUE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_created_at_desc ON dropbox_cursors (created_at DESC);
