name: deploy_queue_files
on:
  push:
    branches:
      - main
    paths:
      - queue_files/main.py
      - queue_files/requirements.txt
      - .github/workflows/deploy_queue_files.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v4"
        with:
          name: "dropbox-queue-files"
          region: "us-west1"
          runtime: "python310"
          entry_point: "run"
          source_dir: "queue_files"
          memory: "256M"
          secrets: "NEON_DATABASE_URL=projects/greg-finley/secrets/NEON_DATABASE_URL/versions/latest,DROPBOX_ACCESS_TOKEN=projects/greg-finley/secrets/DROPBOX_ACCESS_TOKEN/versions/latest,DROPBOX_CONFIG=projects/greg-finley/secrets/DROPBOX_CONFIG/versions/latest"
          service_timeout: "540s"
          event_trigger_pubsub_topic: "projects/greg-finley/topics/dropbox-queue-files"
          min_instance_count: 0
          max_instance_count: 10
