name: deploy_process_file
on:
  push:
    branches:
      - main
    paths:
      - process_file/main.py
      - process_file/requirements.txt
      - .github/workflows/deploy_process_file.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v4"
        with:
          name: "dropbox-backup-function"
          region: "us-west1"
          runtime: "python310"
          entry_point: "run"
          source_dir: "process_file"
          memory: "4096M"
          secrets: "NEON_DATABASE_URL=projects/greg-finley/secrets/NEON_DATABASE_URL/versions/latest"
          service_timeout: "540s"
          event_trigger_pubsub_topic: "projects/greg-finley/topics/dropbox-backup"
          min_instance_count: 0
          max_instance_count: 10
