name: deploy_process_file
on:
  push:
    branches:
      - main
    paths:
      - process_file/main.py
      - process_file/requirements.txt
      - .github/workflows/deploy_process_file.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v1"
        with:
          name: "projects/greg-finley/locations/us-west1/functions/dropbox-backup-function"
          runtime: "python310"
          entry_point: "run"
          source_dir: "process_file"
          memory_mb: 4096
          secret_environment_variables: "NEON_DATABASE_URL=projects/greg-finley/secrets/NEON_DATABASE_URL/versions/latest"
          timeout: 540
          event_trigger_type: "providers/cloud.pubsub/eventTypes/topic.publish"
          event_trigger_resource: "projects/greg-finley/topics/dropbox-backup"
          event_trigger_service: "pubsub.googleapis.com"
          min_instances: 0
          max_instances: 3000
