name: deploy_webhook
on:
  push:
    branches:
      - main
    paths:
      - webhook/main.py
      - webhook/requirements.txt
      - .github/workflows/deploy_webhook.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v4"
        with:
          name: "dropbox-webhook"
          region: "us-west1"
          runtime: "python312"
          entry_point: "run"
          source_dir: "webhook"
          memory: "128M"
          service_timeout: "60s"
          min_instance_count: 0
          max_instance_count: 10
