name: deploy_queue_files
on:
  push:
    branches:
      - main
    paths:
      - queue_files/main.py
      - queue_files/requirements.txt
      - .github/workflows/deploy_queue_files.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v1"
        with:
          name: "projects/greg-finley/locations/us-west1/functions/dropbox-queue-files"
          runtime: "python310"
          entry_point: "run"
          source_dir: "queue_files"
          memory_mb: 256
          secret_environment_variables: "MYSQL_HOST=projects/greg-finley/secrets/MYSQL_HOST/versions/latest,MYSQL_USERNAME=projects/greg-finley/secrets/MYSQL_USERNAME/versions/latest,MYSQL_PASSWORD=projects/greg-finley/secrets/MYSQL_PASSWORD/versions/latest,MYSQL_DATABASE=projects/greg-finley/secrets/MYSQL_DATABASE/versions/latest,DROPBOX_ACCESS_TOKEN=projects/greg-finley/secrets/DROPBOX_ACCESS_TOKEN/versions/latest,DROPBOX_REFRESH_TOKEN=projects/greg-finley/secrets/DROPBOX_REFRESH_TOKEN/versions/latest, DROPBOX_CLIENT_ID=projects/greg-finley/secrets/DROPBOX_CLIENT_ID/versions/latest, DROPBOX_CLIENT_SECRET=projects/greg-finley/secrets/DROPBOX_CLIENT_SECRET/versions/latest"
          timeout: 540
          event_trigger_type: "providers/cloud.pubsub/eventTypes/topic.publish"
          event_trigger_resource: "projects/greg-finley/topics/dropbox-queue-files"
          event_trigger_service: "pubsub.googleapis.com"
          min_instances: 0
          max_instances: 100
